<?php

namespace App\Constants\WebSite;

class LeadSubmission
{
    const PAGE_SOURCE = array(
        'HOME_PAGE', 'CAREER_PAGE', 'CREDIT_SCORE_PAGE', 'ARTICLES_PAGE', 'KNOWLEDGE_CENTER_PAGE', 'APPLY_ONLINE_PAGE', 'GET_A_QUOTE_PAGE',
        'RAISE_A_QUERY_PAGE', 'APPROVED_PROJECT', 'APPROVED_PROPERTIES',
        'E_AUCTION', 'APPROVED_PROPERTIES_GET_CALLBACK', 'APPROVED_PROPERTIES_DREAM_HOME'
    );
    const RULE_TWO_SOURCE_PAGES = array(
        'APPLY_ONLINE_PAGE', 'GET_A_QUOTE_PAGE'
    );
    const RULE_THREE_SOURCE_PAGES = array(
        'ARTICLES_PAGE', 'KNOWLEDGE_CENTER_PAGE', 'APPROVED_PROPERTIES', 'APPROVED_PROPERTIES_GET_CALLBACK', 'APPROVED_PROPERTIES_DREAM_HOME', 'E_AUCTION'
    );
}
